# Generated by Django 3.2.6 on 2024-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='answer',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
